name: Tailscale GitOps ACL action
description: Validates or applies a Tailscale ACL policy file

inputs:
  tailnet:
    description: "Tailnet name (eg. example.com, xe.github, tailscale.org.github)"
    required: true
  api-key:
    description: "Tailscale API key"
    required: false
  oauth-client-id:
    description: "Tailscale OAuth ID"
    required: false
  oauth-secret:
    description: "Tailscale OAuth Secret"
    required: false
  policy-file:
    description: "Path to policy file"
    required: true
    default: ./policy.hujson
  action:
    description: "Action to take (test/apply)"
    required: true


runs:
  using: docker
  image: docker://ghcr.io/kdkasad/tailscale-acl-action:0.1.1
  args:
    - --policy-file=${{ inputs.policy-file }}
    - ${{ inputs.action }}
  env:
    TS_OAUTH_ID: "${{ inputs.oauth-client-id }}"
    TS_OAUTH_SECRET: "${{ inputs.oauth-secret }}"
    TS_API_KEY: "${{ inputs.api-key }}"
    TS_TAILNET: "${{ inputs.tailnet }}"
